### ISSUE TITLE
[1.17] Server stalls on boot 

### ISSUE THREAD

**Issue by 0swin** [Sefiraat/EquivalencyTech#9]
**Description :** 
The server loads correctly until it starts to load EquiTech plugin
I have seen other issues on this subject (#4) but I can't try to edit the config as it's the first time I run my server with EquiTech, so the config isnt generated yet

**Plugins (29) :**
Brewery, ChestTerminal, ColoredEnderChests, DankTech, DriveBackupV2, DyedBackpacks, DynaTech, dynmap, EcoPower, FastLeafDecay, FluffyMachines, GeneticChickengineering, GSit, LiteXpansion, LuckPerms, Multiverse-Core, ProtocolLib, SetHomes, SFCalc, SilkSpawners, SimpleStorage, SimpleUtils, SkinsRestorer, Slimefun, SlimefunOreChunks, SlimyTreeTaps, SoundMuffler, ViaBackwards, ViaVersion

**Log file :** 
https://pastebin.com/VNSHk1ek

**Comment by Sefiraat** [comment]
If you begin by downloading the default config file from [here](https://github.com/Sefiraat/EquivalencyTech/blob/master/src/main/resources/config.yml). Place it in the EquivalencyTech folder (create one if there isn't one yet). Change the `SHOW_DEBUGGING_LOGS: false` to `SHOW_DEBUGGING_LOGS: true`.
When you next load the server, you will get a LOT of spam. It should become clear enough when the process is looping on itself. At this point you can force close the server and send those logs.

Sorry for this, bear with an ill have it fixed in a jif :)

**Comment by 0swin** [comment]
Thanks !
It seems that it loops once it reaches EMC TESTING : STONE_STAIRS
https://pastebin.com/GpB69K2Z

**Comment by Sefiraat** [comment]
Interesting, not sure why this would be a new issue nor why it would be on a non-1.17 item. i'll look into this more when Im back from work. Until then, you could add a custom EMC value for STONE_STAIRS in the config file and try again, though I would imagine you may find others like this as you go which may make this a horrible experience.

**Comment by 0swin** [comment]
Added a custom value for STONE_STAIRS, now it stucks at STONE_SLABS
Won't do all manually, as I don't know how much time it'll take me, also I don't know what values to put to not unbalance your plugin hahaha
Do you think ViaVersion/ViaBackwards could be the source from this issue ? They allow to use older versions of minecraft, maybe it affects how the blocs are managed ?

**Comment by 0swin** [comment]
Desactivated ViaVersion/ViaBackwards, they are not source of the issue

**Comment by Sefiraat** [comment]
The only difference I am seeing is you're using Purpur, which I have have seen in previous reports. It's not something I test against or would normally would be willing to make a fix for. Though that may be a red herring. I will have to explore in more depth 😄

**Comment by 0swin** [comment]
I'll reboot on Paper and keep you updated

**Comment by 0swin** [comment]
I have the exact same issue on paper-1.17.1-100 😢

**Comment by Sefiraat** [comment]
Hi 0swin, 

I have tried this again myself on paper-1.17.1-100 and I cannot recreate the issue.
This would narrow it down to one of you plugins so please can you try removing a set until you are able to boot and this will let us know which is causing the issue, then I can look into that specific plugin and try to add a work around/fix.

As a side-note, GeneticChickengineering is known to not work in modern versions of minecraft/slimefun and is *effectively* abandoned. Hopefully this changes but it may need to be removed.

**Comment by 0swin** [comment]
I just spend a little bit of time trying to disable each plugin one by one to find the one causing an issue. I reached the point where my only plugins were Slimefun and EquiTech, the issue remained.

The only way I found to not have this issue was to delete my world and create a new one.
I have now found the issue, it comes from my datapacks ! I have the datapack "Back to Blocks" from Vanilla Tweaks, that allows to create full blocks from slabs or stairs, creating the loop in EquiTech !

Thanks for helping me along this 😇
You could probably add an incompatibility section do the readme if this issue isn't fixable

Also thanks for the note on GeneticChickengineering, I have disabled it now

**Comment by Sefiraat** [comment]
I had coded in a "if this has taken 15 attempts, give up" which clearly isnt working. Ill look up that datapack and make this either work or give up, rather than stall like this, as its very bad to experience.

Ill close this for now, thanks very much for your help, and ill comment on this issue again when I change something that will either fix or bypass this.

Thanks! Sefi
